name: acecoderv2-dev
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # Base Python environment
  - python=3.10
  - pip
  
  # Scientific computing
  - numpy>=2.0
  - pandas>=2.0
  
  # Deep learning frameworks
  - pytorch>=2.0
  - pytorch-cuda=12.8  # CUDA support
  
  # Development tools
  - git
  - curl
  - wget
  
  # Pip dependencies
  - pip:
      # Core project dependencies
      - fire>=0.7.0
      - datasets>=4.0.0
      - transformers>=4.53.3
      - openai>=1.97.1
      - huggingface-hub>=0.34.0
      
      # Web interface
      - gradio>=5.0.0
      - fastapi>=0.110.0
      - uvicorn>=0.25.0
      
      # Evaluation
      - evalplus>=0.3.0
      
      # Development dependencies
      - accelerate>=1.0.0
      - tokenizers>=0.21.0
      - safetensors>=0.6.0
      
      # AceCoder package (install from source)
      - git+https://github.com/TIGER-AI-Lab/AceCoder.git@dev
